name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ami: ${{ steps.manifest.outputs.ami }}
    container:
      image: hashicorp/packer:1.8.2
      env:
        PKR_VAR_server: 'paper'
        PKR_VAR_version: '1.19.1'
        PKR_VAR_download_url: https://api.papermc.io/v2/projects/paper/versions/1.19.1/builds/86/downloads/paper-1.19.1-86.jar
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v3
      - name: Setup testinfra
        run: |
          apk add python3 py3-pip
          pip install -r requirements.txt
      - name: Packer build
        run: |
          packer init build.pkr.hcl
          packer validate build.pkr.hcl
          packer build build.pkr.hcl
      - name: Parse Manifest
        id: manifest
        run: |
          apk add jq
          ami=$(jq -r '.builds[-1].artifact_id' packer-manifest.json | cut -d ":" -f2)
          echo "::set-output name=ami::$ami"
      - name: Upload manifest
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Packer manifest
          path: packer-manifest.json

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: hashicorp/packer:1.8.2
      env:
        PKR_VAR_ami: ${{ needs.build.outputs.ami }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v3
      - name: Setup testinfra
        run: |
          apk add python3 py3-pip
          pip install -r requirements.txt
      - name: Test the Image
        run: |
          packer init test.pkr.hcl
          packer validate test.pkr.hcl
          packer build test.pkr.hcl

  scan:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: hashicorp/packer:1.8.2
      env:
        PKR_VAR_ami: ${{ needs.build.outputs.ami }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v3
      - name: Scan the Image
        run: |
          packer init scan.pkr.hcl
          packer validate scan.pkr.hcl
          packer build scan.pkr.hcl
      - name: Upload SBOM
        uses: actions/upload-artifact@v3.1.0
        with:
          name: SBOM
          path: sbom.json
      - name: Upload vulnerability report
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Vulnerability report
          path: vulnerabilities.txt
