name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/packer:1.8.2
      env:
        PKR_VAR_server: 'paper'
        PKR_VAR_version: '1.19'
        PKR_VAR_download_url: https://api.papermc.io/v2/projects/paper/versions/1.19/builds/68/downloads/paper-1.19-68.jar
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v3
      - name: Setup testinfra
        run: |
          apk add python3 py3-pip
          pip install -r requirements.txt
      - name: Packer build
        run: |
          packer init minecraft-server-ami.pkr.hcl
          packer validate minecraft-server-ami.pkr.hcl
          packer build minecraft-server-ami.pkr.hcl
